server:
  port: 8080
  shutdown: graceful

logging:
  level:
    org.springframework: INFO
    org.springframework.boot: INFO


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bench_test
    username: pk_bench
    password: 'Tkdgus0403!'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create   # ??/???: create, create-drop, update / ??: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect